package ExceptionHandling;

public class ExceptionHandlingRunner2 {

	public static void main(String[] args) {
		method01();
		System.out.println("main ended");
	}

	private static void method01() {
		try{
			method02();
		}catch (Exception ex) {
			System.out.println("Matched Exception");
			ex.printStackTrace();
		}
		System.out.println("method01 ended");
	}

	private static void method02() {
		try {
//			String str = null;
//			str.length();
			int[] i = { 1, 2 };
			System.out.println(i[3]); // 요놈은 NullPointException이 아니라 밑에꺼는 걸러짐
			System.out.println("응 이건 안보여~");
		} catch (NullPointerException ex) {
			System.out.println("Matched NullPointerException");
			ex.printStackTrace();
		} 
		System.out.println("method02 ended");
	}

}
